### ISSUE TITLE
导包之后看不到原文件

### ISSUE THREAD

**Issue by YenalyLiew** [TxcA/SpannableX#1]
只有class，download source失败
Supplied String module notation 'com.itxca.spannablex:spannablex:1.0.0:debug@aar:sources' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.

**Comment by TxcA** [comment]
`gradle-maven-publish-plugin` 更新0.19.0后，默认打包了全部`variants`，也就是同时发布了`debug` + `release`包。
引用的时候由于`variant`是debug，导致错误的下载了`spannablex:1.0.0:debug@aar`，所以看不到源码。

当初发布的时候自己没有注意到0.19.0的这个变化，由于mavenCentral不能覆盖已发布的数据，请升级`1.0.2`：

```groovy
implementation 'com.itxca.spannablex:spannablex:1.0.2'
```

🎈 [gradle-maven-publish-plugin CHANGELOG](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/CHANGELOG.md#version-0190-2022-02-26)

---

**无1.0.1:**  *最初以为是忘记加打包源码了，所以加上后发布了`1.0.1`但并未解决问题。*

@YenalyLiew **感谢提醒！**
