### ISSUE TITLE
建议添加QuoteSpan

### ISSUE THREAD

**Issue by YenalyLiew** [TxcA/SpannableX#3]
自带的QuoteSpan的API要求较高，如果该库整合的话能更方便调用一些

**Comment by TxcA** [comment]
目前只添加了字符相关的效果。
等我我整理下段落相关的效果，一并更新。

**Comment by TxcA** [comment]
`SpannableX 1.0.4`已新增`ParagraphStyle`段落相关样式支持，其中包含了`QuoteSpan`.
```
dependencies {
    // https://github.com/TxcA/SpannableX
    implementation 'com.itxca.spannablex:spannablex:1.0.4'

}
```
---
详见 [更新说明](https://txca.github.io/SpannableX/change/) 

或 [常用Span](https://txca.github.io/SpannableX/spans/) 介绍
