### ISSUE TITLE
点击没反应呢

### ISSUE THREAD

**Issue by LxzBUG** [TxcA/SpannableX#4]
"《用户协议》".span {
            color("#0068FE")
            clickable(onClick = { v, matchText ->
              startActivity(Intent(this@LoginActivity,WebActivity::class.java).apply {
                putExtra("type",0)
              })
            })
          }

**Comment by TxcA** [comment]
点击需配合`activateClick`


详见 [TextView.activateClick](https://txca.github.io/SpannableX/utils/#textviewactivateclickboolean)

**Comment by LxzBUG** [comment]
谢谢 @TxcA
